# Generated by Django 4.1.7 on 2023-02-16 07:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("app_forum", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
