# Generated by Django 4.1.7 on 2023-02-16 07:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_forum", "0002_post_date_topic_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="time",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="time",
        ),
    ]
