# Generated by Django 4.1.7 on 2023-02-21 08:22

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("app_forum", "0003_remove_post_time_remove_topic_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="app_forum.topic",
            ),
        ),
    ]
