# Generated by Django 4.1.7 on 2023-03-07 08:09

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("app_forum", "0006_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="tag",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
